# Generated by Django 5.0.2 on 2024-02-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
