# Generated by Django 5.0.2 on 2024-02-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_data_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
